slam_toolbox:
  ros__parameters:
    odom_frame: "odom"
    map_frame: "map"
    base_frame: "base_footprint"
    scan_topic: "/scan"

    use_sim_time: true

  
    mode: "mapping"
    map_update_interval: 2.0
    resolution: 0.05
    max_laser_range: 3.5
    use_scan_matching: true
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.15