slam_toolbox:
  ros__parameters:
    # MANDATORY PARAMETERS - Using your Digital Twin's namespaced topics/frames
    odom_frame: "my_tb3/odom"          # Your DT's odometry frame
    map_frame: "map"                   # The map frame to be created
    base_frame: "base_footprint"  # Your DT's base frame
    scan_topic: "/my_tb3/scan"         # Your DT's LIDAR topic

    use_sim_time: True                 # Crucial for Gazebo simulation

    # Other common parameters (adjust if needed, defaults are often okay for a start)
    mode: "mapping"                    # "mapping" or "localization"
    map_update_interval: 2.0           # How often to update the map (seconds)
    resolution: 0.05                   # Map resolution in meters/pixel
    max_laser_range: 3.5               # Max range of your LIDAR (for TB3 LDS-01)

    # Settings for map quality
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.15 # Radians

    # For Foxy, solver_plugin might not be explicitly needed or might default if Ceres isn't fully set up.
    # If you face issues, you can try commenting out the solver_plugin line.
    # solver_plugin: "solver_plugins::CeresSolver"
